---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ include "node-build.name" . }}-el
  labels:
    {{- include "node-build.labels" . | nindent 4 }}
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: {{ include "node-build.name" . }}-commit-binding
      interceptors:
        - params:
            - name: filter
              value: has(body.commits) && body.object_kind == 'push'
            - name: overlays
              value: null
          ref:
            kind: ClusterInterceptor
            name: cel
      name: commit-trigger
      template:
        ref: {{ include "node-build.name" . }}-build
