apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "node-build.name" . }}-pipeline-run-job
  labels:
    {{- include "node-build.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector: {}
  template:
    metadata:
      name: {{ include "node-build.name" . }}-pipeline-run-job
    spec:
      containers:
        - name: {{ include "node-build.name" . }}-pipeline-run-job
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - '-ec'
            - >-
              oc create -f /scripts/trigger-pipeline.yaml
          volumeMounts:
            - mountPath: /scripts
              name: {{ include "node-build.name" . }}-script-vol
      restartPolicy: OnFailure
      serviceAccountName: pipeline
      volumes:
      - name: {{ include "node-build.name" . }}-script-vol
        configMap:
          name: {{ include "node-build.name" . }}-trigger-pipeline

