{{- if eq .Values.image.registry "Quay" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orders-backend.name" . }}-registry-creds-app
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: | 
    {
      "username": "{{ .Values.image.organization }}",
      "password": "{{ .Values.image.password }}",
      "auths": {
        "{{ .Values.image.host }}": {
          "auth": "{{ include "quay.auth" . }}"
        }
      }
    }
{{- end }}