apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "orders-build.name" . }}-external-webhook-secret
  labels:
    {{- include "orders-build.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "orders-build.name" . }}-webhook-secret
  data:
  - secretKey: secret
    remoteRef:
      key: secrets/rhdh/gitlab_webhook
      property: secret

