apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "orders-build.name" . }}-external-git-token
  labels:
    {{- include "orders-build.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "orders-build.name" . }}-git-token
  data:
  - secretKey: token
    remoteRef:
      key: secrets/rhdh/gitlab
      property: token

