apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "orders-build.name" . }}-webhook-job
  labels:
    {{- include "orders-build.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: create-webhook
        command:
          - /bin/bash
          - '-c'
          - |
            set -x
            ansible-playbook -i localhost /scripts/playbook.yaml -e git_token=$(cat /tokens/token) -e webhook_secret=$(cat /secrets/secret)
        image: quay.io/agnosticd/ee-multicloud:latest
        volumeMounts:
          - mountPath: /scripts
            name: {{ include "orders-build.name" . }}-script-vol
          - mountPath: /tokens
            name: git-token
          - mountPath: /secrets
            name: webhook-secret
      restartPolicy: Never
      volumes:
        - name: {{ include "orders-build.name" . }}-script-vol
          configMap:
            name: {{ include "orders-build.name" . }}-webhook-script
        - name: git-token
          secret:
            secretName: {{ include "orders-build.name" . }}-git-token
        - name: webhook-secret
          secret:
            secretName: {{ include "orders-build.name" . }}-webhook-secret
