{{- if eq .Values.image.registry "Quay" }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
secrets:
  - name: {{ include "orders-build.name" . }}-registry-creds
imagePullSecrets:
  - name: {{ include "orders-build.name" . }}-registry-creds
{{- end }}
