{{- if .Values.postgresql.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.namespace }}
  labels:
    template: postgresql-ephemeral-template
    {{- include "store-common-config.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
    argocd.argoproj.io/sync-wave: "0"
data:
  database-name: {{ .Values.postgresql.database | b64enc }}
  database-password: {{ .Values.postgresql.password | b64enc }}
  database-user: {{ .Values.postgresql.user | b64enc }}
type: Opaque
{{- end }}

