{{- if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "store-common-config.labels" . | nindent 4 }}
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: '3.3'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
    replicas: {{ .Values.kafka.replicas }}
    storage:
      type: ephemeral
    version: {{ .Values.kafka.version }}
  zookeeper:
    replicas: {{ .Values.kafka.replicas }}
    storage:
      type: ephemeral
{{- end }}

