{{- if .Values.kafkaTopic.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
    {{- include "store-common-config.labels" . | nindent 4 }}
  name: {{ .Values.kafkaTopic.name }}
  namespace: {{ .Values.namespace }}
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: {{ .Values.kafkaTopic.partitions }}
  replicas: {{ .Values.kafkaTopic.replicas }}
{{- end }}

