---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}
  namespace: rhdh-gitops
  labels:
    rht-gitops.com/${{ values.gitops_namespace }}: ${{ values.component_id }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: ${{ values.source_repository_gitops }}
    targetRevision: HEAD
    path: ./helm/app
    helm:
      values: |
        nameOverride: ${{ values.component_id }}
        imagePullSecrets:
          - name: ${{ values.component_id }}-registry-creds-app
        user: ${{ values.owner }}
        service:
          port: ${{values.port}}
        image:
          registry: ${{values.image_registry}}
          organization: ${{values.image_organization}}
          host: ${{ values.image_host }}
          name: ${{ values.image_name }}
          namespace: ${{ values.namespace }}
          tag: ${{ values.image_tag }}
          password: ${{values.image_password}}
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdh-gitops
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ${{ values.gitops_namespace }}
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
